language: ruby
sudo: false
dist: trusty
rvm:
- 2.4.0
before_install: wget https://releases.hashicorp.com/packer/1.2.2/packer_1.2.2_linux_amd64.zip
  && unzip -d packer packer_1.2.2_linux_amd64.zip
before_script: export PATH=$PWD/packer:$PATH

script: bundle exec thor packer:validate
notifications:
  slack:
    secure: ohPy5LBZD5NGfkkcLARb76330m8HtSDgNEAEljdkJ8NpCRaH0TFX/aVun8u6tOqdfXGH2wr/R+Aoghi0bbP+d+C5DOoIfa1nURPshkHF/2mZf2QuMrbQALPfv2l3FSlWuMfX9a8th3F1t/L3mj9qVKqYFWHlBOmHl6QrSpOKXFY=
